mostpopular:
    pattern:  /
    defaults: { _controller: TikitTikitBundle:Petition:mostpopular }

tikit_tikitsss:
    resource: "@TikitTikitBundle/Controller/TikitController.php"
    type:     annotation
    prefix:   /t

tikit_tikit:
    path: /t/{id}
    defaults:  { _controller: TikitTikitBundle:Tikit:tikit }

tikit_tikits:
    path: /main/{page}
    defaults:  { _controller: TikitTikitBundle:Tikit:tikits }

_tikit_addcomment:
    path: /addcomment/
    defaults:  { _controller: TikitTikitBundle:Comment:addcomment }

_tikit_addtikitvote:
    path: /addtikitvote/
    defaults:  { _controller: TikitTikitBundle:Tikit:vote }

_tikit_loadlinkdata:
    path: /loadlinkdata/
    defaults:  { _controller: TikitTikitBundle:Tikit:loadlinkdata }

_tikit_addtikit:
    path: /addtikit/tikit
    defaults:  { _controller: TikitTikitBundle:Tikit:addtikit }
    
petition_create:
    path: /p/create
    defaults:  { _controller: TikitTikitBundle:Petition:create }
    
petition:
    path: /p/index
    defaults:  { _controller: TikitTikitBundle:Petition:index }
petition_show:
    path: /p/{url}
    defaults:  { _controller: TikitTikitBundle:Petition:show }
petition_delete:
    path: /p/delete/{id}
    defaults:  { _controller: TikitTikitBundle:Petition:delete }
petition_edit:
    path: /p/edit/{id}
    defaults:  { _controller: TikitTikitBundle:Petition:edit }
petition_update:
    path: /p/update/{id}
    defaults:  { _controller: TikitTikitBundle:Petition:update }
petition_new:
    path: /p/create
    defaults:  { _controller: TikitTikitBundle:Petition:create }

petition_petitions:
    path: /petit/{page}
    defaults:  { _controller: TikitTikitBundle:Petition:petitions }   
bycategory:
    path: /category/{category}
    defaults:  { _controller: TikitTikitBundle:Petition:bycategory } 

_votepetition:
    path: /votepetition
    defaults:  { _controller: TikitTikitBundle:Petition:votepetition }