parameters:
#    tikit_tikit.example.class: Tikit\TikitBundle\Example

services:
#    tikit_tikit.example:
#        class: %tikit_tikit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tikit.model.tikitmodel:
        class:  Tikit\TikitBundle\Service\TikitModel
        arguments: ["@doctrine.orm.entity_manager"]
            #entityManager: "@doctrine.orm.entity_manager"
    petition.model.petitionmodel:
        class:  Tikit\TikitBundle\Service\PetitionModel
        arguments: ["@doctrine.orm.entity_manager"]
            